<?php echo $this->doctype(); ?>

<html lang="pt">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Quero um iphone')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/jquery-ui.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

</head>
<body>

<div class="container-fluid">
    <div class="row my-row">
        <div class="col-lg-12-col-md-12 col-sm-12 col-xs-12 my-col">
            <?php echo $this->content; ?>
        </div>
    </div>
</div>

<!-- Scripts -->
<?php echo $this->inlineScript()
    ->prependFile($this->basePath('js/main.min.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery-ui.min.js'))
    ->prependFile($this->basePath('js/jquery.mask.min.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
    ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
?>

</body>
</html>
