<div class="banner-content-blog">
    <div class="container-fluid banner-blog">
        <div class="row my-row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 my-col">
                <div class="container">
                    <div class="row my-row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="content-slogan">
                                <h2>Acesse nosso sistema</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="login">
    <div class="container-fluid banner-blog">
        <div class="row my-row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 my-col">
                <div class="container">
                    <div class="row my-row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="content-login">
                                <?php $form = $this->form; ?>
                                <?php $form->setAttribute('onSubmit', 'event.preventDefault();authenticate();'); ?>
                                <?php $form->setAttribute('stlye', "background-color:white;"); ?>
                                <?php $form->prepare(); ?>
                                <?php echo $this->form()->openTag($form); ?>
                                <?php echo $this->formhidden($form->get('csrf')); ?>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="form-group">
                                            <?php echo $this->formrow($form->get('login')); ?>
                                        </div>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <div class="form-group">
                                            <?php echo $this->formrow($form->get('password')); ?>
                                        </div>
                                    </div>
                                </div>
                                <!--alert-->
                                <div class="row alert-row">
                                    <div class="col-md-12" id="alert-login"></div>
                                </div>
                                <!--alert-->
                                <div class="row">
                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                        <?php  echo $this->formsubmit($form->get('submit')); ?>
                                    </div>
                                </div>
                                <?php echo $this->form()->closeTag(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container-form-loginUser">

</div>

