<?php

namespace DoctrineORMModule\Proxy\__CG__\Client\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \Client\Entity\User implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userId', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userUsername', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userPassword', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userSalt', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userActivationKey', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userStatus', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userCreatedAt', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userUpdatedAt', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'role'];
        }

        return ['__isInitialized__', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userId', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userUsername', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userPassword', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userSalt', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userActivationKey', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userStatus', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userCreatedAt', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'userUpdatedAt', '' . "\0" . 'Client\\Entity\\User' . "\0" . 'role'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (User $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getUserId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getUserId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserId', []);

        return parent::getUserId();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserId($userId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserId', [$userId]);

        return parent::setUserId($userId);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserUsername()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserUsername', []);

        return parent::getUserUsername();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserUsername($userUsername)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserUsername', [$userUsername]);

        return parent::setUserUsername($userUsername);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserPassword()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserPassword', []);

        return parent::getUserPassword();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserPassword($userPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserPassword', [$userPassword]);

        return parent::setUserPassword($userPassword);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserSalt', []);

        return parent::getUserSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserSalt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserSalt', []);

        return parent::setUserSalt();
    }

    /**
     * {@inheritDoc}
     */
    public function getUserActivationKey()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserActivationKey', []);

        return parent::getUserActivationKey();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserActivationKey($userActivationKey)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserActivationKey', [$userActivationKey]);

        return parent::setUserActivationKey($userActivationKey);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserStatus', []);

        return parent::getUserStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserStatus($userStatus)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserStatus', [$userStatus]);

        return parent::setUserStatus($userStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserCreatedAt', []);

        return parent::getUserCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserCreatedAt($userCreatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserCreatedAt', [$userCreatedAt]);

        return parent::setUserCreatedAt($userCreatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getUserUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUserUpdatedAt', []);

        return parent::getUserUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setUserUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUserUpdatedAt', []);

        return parent::setUserUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function getRole()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getRole', []);

        return parent::getRole();
    }

    /**
     * {@inheritDoc}
     */
    public function setRole($role)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setRole', [$role]);

        return parent::setRole($role);
    }

    /**
     * {@inheritDoc}
     */
    public function encryptPassword($userPassword)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'encryptPassword', [$userPassword]);

        return parent::encryptPassword($userPassword);
    }

}
