<?php

namespace DoctrineORMModule\Proxy\__CG__\Client\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Contact extends \Client\Entity\Contact implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Client\\Entity\\Contact' . "\0" . 'contactId', '' . "\0" . 'Client\\Entity\\Contact' . "\0" . 'contactName', '' . "\0" . 'Client\\Entity\\Contact' . "\0" . 'contactPhone1', '' . "\0" . 'Client\\Entity\\Contact' . "\0" . 'contactPhone2', '' . "\0" . 'Client\\Entity\\Contact' . "\0" . 'contactCreatedAt', '' . "\0" . 'Client\\Entity\\Contact' . "\0" . 'contactUpdatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'Client\\Entity\\Contact' . "\0" . 'contactId', '' . "\0" . 'Client\\Entity\\Contact' . "\0" . 'contactName', '' . "\0" . 'Client\\Entity\\Contact' . "\0" . 'contactPhone1', '' . "\0" . 'Client\\Entity\\Contact' . "\0" . 'contactPhone2', '' . "\0" . 'Client\\Entity\\Contact' . "\0" . 'contactCreatedAt', '' . "\0" . 'Client\\Entity\\Contact' . "\0" . 'contactUpdatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Contact $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getContactId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getContactId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactId', []);

        return parent::getContactId();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactId($contactId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactId', [$contactId]);

        return parent::setContactId($contactId);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactName', []);

        return parent::getContactName();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactName($contactName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactName', [$contactName]);

        return parent::setContactName($contactName);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactPhone1()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactPhone1', []);

        return parent::getContactPhone1();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactPhone1($contactPhone1)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactPhone1', [$contactPhone1]);

        return parent::setContactPhone1($contactPhone1);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactPhone2()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactPhone2', []);

        return parent::getContactPhone2();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactPhone2($contactPhone2)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactPhone2', [$contactPhone2]);

        return parent::setContactPhone2($contactPhone2);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactCreatedAt', []);

        return parent::getContactCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactCreatedAt($contactCreatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactCreatedAt', [$contactCreatedAt]);

        return parent::setContactCreatedAt($contactCreatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getContactUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContactUpdatedAt', []);

        return parent::getContactUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setContactUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContactUpdatedAt', []);

        return parent::setContactUpdatedAt();
    }

}
