<?php

namespace DoctrineORMModule\Proxy\__CG__\Client\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Address extends \Client\Entity\Address implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressId', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressName', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressZipcode', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressCity', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressState', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressCreatedAt', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressUpdatedAt'];
        }

        return ['__isInitialized__', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressId', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressName', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressZipcode', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressCity', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressState', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressCreatedAt', '' . "\0" . 'Client\\Entity\\Address' . "\0" . 'addressUpdatedAt'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Address $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getAddressId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getAddressId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressId', []);

        return parent::getAddressId();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressId($addressId)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressId', [$addressId]);

        return parent::setAddressId($addressId);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressName', []);

        return parent::getAddressName();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressName($addressName)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressName', [$addressName]);

        return parent::setAddressName($addressName);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressZipcode()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressZipcode', []);

        return parent::getAddressZipcode();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressZipcode($addressZipcode)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressZipcode', [$addressZipcode]);

        return parent::setAddressZipcode($addressZipcode);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressCity()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressCity', []);

        return parent::getAddressCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressCity($addressCity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressCity', [$addressCity]);

        return parent::setAddressCity($addressCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressState()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressState', []);

        return parent::getAddressState();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressState($addressState)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressState', [$addressState]);

        return parent::setAddressState($addressState);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressCreatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressCreatedAt', []);

        return parent::getAddressCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressCreatedAt($addressCreatedAt)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressCreatedAt', [$addressCreatedAt]);

        return parent::setAddressCreatedAt($addressCreatedAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddressUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddressUpdatedAt', []);

        return parent::getAddressUpdatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddressUpdatedAt()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddressUpdatedAt', []);

        return parent::setAddressUpdatedAt();
    }

}
