<div class="container">
    <div class="row my-row">
        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 my-col">
            <!--form-->
            <?php $form = $this->form; ?>
            <?php $form->setAttributes(array(
                'id' => 'storeClient',
                'onsubmit' => 'event.preventDefault();storeClient()'
            ));
            ?>
            <?php $form->prepare(); ?>
            <?php echo $this->form()->openTag($form); ?>
            <?php echo $this->formhidden($form->get('csrf')); ?>

            <?php echo $this->formrow($form->get('client_name')); ?>
            <?php echo $this->formrow($form->get('client_cpf')); ?>
            <?php echo $this->formrow($form->get('client_cnpj')); ?>
            <?php echo $this->formrow($form->get('client_email')); ?>
            <?php echo $this->formrow($form->get('user_username')); ?>
            <?php echo $this->formrow($form->get('user_password')); ?>
            <?php echo $this->formrow($form->get('user_password_confirm')); ?>
            <?php echo $this->formrow($form->get('address_name')); ?>
            <?php echo $this->formrow($form->get('address_zipcode')); ?>
            <?php echo $this->formrow($form->get('address_city')); ?>
            <?php echo $this->formrow($form->get('address_state')); ?>
            <?php echo $this->formrow($form->get('contact_name')); ?>
            <?php echo $this->formrow($form->get('contact_phone_1')); ?>
            <?php echo $this->formrow($form->get('contact_phone_2')); ?>

            <div class="row my-row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 my-col">
                    <p>* Campos obrigatórios</p>
                </div>
            </div>

            <!--alert-->
            <div class="row my-row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 my-col">
                    <div id="alert-client"></div>
                </div>
            </div>
            <!--alert-->

            <?php echo $this->formrow($form->get('submit')); ?>

            <?php echo $this->form()->closeTag(); ?>
            <!--form-->
        </div>
    </div>
</div>