<div class="banner-content-blog">
    <div class="container-fluid banner-blog">
        <div class="row my-row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 my-col">
                <div class="container">
                    <div class="row my-row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="content-slogan">
                                <h2>Cadastre-se e acesse nossa plataforma</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="form">
    <div class="container-fluid">
        <div class="row my-row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 my-col">
                <div class="row my-row">
                    <div class="container">
                        <div id="tabs">
                            <div class="tabs">
                                <ul>
                                    <li>
                                        <a href="#dados-de-contato" class="dados-de-contato go-to-dados-pessoais-e-endereco">Dados de contato</a>
                                    </li>
                                    <li>
                                        <a href="#dados-pessoais-e-endereco" class="dados-pessoais-e-endereco go-to-dados-de-acesso back-to-dados-de-contato">Dados pessoais e endereço</a>
                                    </li>
                                    <li>
                                        <a href="#dados-de-acesso" class="dados-de-acesso back-to-dados-pessoais-e-endereco">Dados de acesso</a>
                                    </li>
                                </ul>
                            </div>
                            <!--form-->
                            <?php $form = $this->form; ?>
                            <?php $form->setAttributes(array(
                                'id' => 'storeClient',
                                'onsubmit' => 'event.preventDefault();storeClient()'
                            ));
                            ?>
                            <?php $form->prepare(); ?>
                            <?php echo $this->form()->openTag($form); ?>
                            <?php echo $this->formhidden($form->get('csrf')); ?>
                            <div class="row my-row">
                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="dados-de-contato">
                                            <div class="dados-content">
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('client_name')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('client_email')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('contact_name')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('contact_phone_1')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('contact_phone_2')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row next">
                                                    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12"></div>
                                                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                                        <button type="button" class="btn btn-default btn-go-to" id="go-to-dados-pessoais-e-endereco">Próximo</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="dados-pessoais-e-endereco">
                                            <div class="dados-content">
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('client_cpf')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('client_cnpj')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('address_zipcode')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('address_name')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('address_city')); ?>
                                                        </div>
                                                    </div>
                                                    <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('address_state')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row next">
                                                    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                                                        <button type="button" class="btn btn-default btn-back-to" id="back-to-dados-de-contato">Anterior</button>
                                                    </div>
                                                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                                        <button type="button" class="btn btn-default btn-go-to" id="go-to-dados-de-acesso">Próximo</button>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12" id="dados-de-acesso">
                                            <div class="dados-content">
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('user_username')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('user_password')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div class="form-group">
                                                            <?php echo $this->formrow($form->get('user_password_confirm')); ?>
                                                        </div>
                                                    </div>
                                                </div>
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <p>* Campos obrigatórios</p>
                                                    </div>
                                                </div>
                                                <!--alert-->
                                                <div class="row">
                                                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                                                        <div id="alert-client"></div>
                                                    </div>
                                                </div>
                                                <!--alert-->
                                                <div class="row">
                                                    <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
                                                        <button type="button" class="btn btn-default btn-back-to" id="dados-pessoais-e-endereco">Anterior</button>
                                                    </div>
                                                    <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                                                        <?php echo $this->formrow($form->get('submit')); ?>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <?php echo $this->form()->closeTag(); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
