<div class="dashboard">
    <div class="container-fluid">
        <div class="row my-row">
            <?php include 'menu-lateral.phtml'; ?>
            <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 my-col">
                <div class="row my-row">
                    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 content-dashboard">
                        <div class="content">
                            teste
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>