<div class="col-lg-2 col-md-2 col-sm-2 col-xs-12 my-col">
    <div id="accordion" class="menu-lateral">
        <h3>Cliente</h3>
        <div class="client">
            <ul>
                <li><a href="#">Meus dados</a></li>
            </ul>
        </div>
        <h3>Solicitações</h3>
        <div class="solicitacoes">
            <ul>
                <li><a href="#">Meus Orçamentos</a></li>
                <li><a href="#">Novo Orçamento</a></li>
            </ul>
        </div>
        <h3>EAD</h3>
        <div class="ead">
            <ul>
                <li><a href="#">Meus Cursos</a></li>
                <li><a href="#">Novo Curso</a></li>
            </ul>
        </div>
    </div>
</div>