<div class="banner-content-blog">
    <div class="container-fluid banner-blog">
        <div class="row my-row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 my-col">
                <div class="container">
                    <div class="row my-row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <div class="content-slogan">
                                <h2>Cadastre-se e acesse nossa plataforma de EAD gratuita</h2>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="form">
    <div class="container-fluid form">
        <div class="container dados-content">
            <!--form-->
            <?php $form = $this->form; ?>
            <?php $form->setAttributes(array(
                'id' => 'storeStudent',
                'onsubmit' => 'event.preventDefault();storeStudent()'
            ));
            ?>
            <?php $form->prepare(); ?>
            <?php echo $this->form()->openTag($form); ?>
            <?php echo $this->formhidden($form->get('csrf')); ?>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-group">
                        <?php echo $this->formrow($form->get('student_name')); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-group">
                        <?php echo $this->formrow($form->get('student_email')); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-group">
                        <?php echo $this->formrow($form->get('user_username')); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-group">
                        <?php echo $this->formrow($form->get('user_password')); ?>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="form-group">
                        <?php echo $this->formrow($form->get('user_password_confirm')); ?>
                    </div>
                </div>
            </div>
            <!--alert-->
            <div class="row">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div id="alert-student"></div>
                </div>
            </div>
            <!--alert-->
            <div class="row next">
                <div class="col-lg-9 col-md-9 col-sm-9 col-xs-12"></div>
                <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
                    <?php echo $this->formrow($form->get('submit')); ?>
                </div>
            </div>
            <?php echo $this->form()->closeTag(); ?>
        </div>
    </div>
</div>
