<?php echo $this->doctype(); ?>

<html lang="pt">
<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('Quero um iphone')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.min.css')) ?>

</head>
<body>
<!--header-->
<header class="header">
    <div class="container-fluid">
        <div class="row my-row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 my-col">
                <div class="container">
                    <div class="row my-row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 my-col">
                            <nav class="navbar navbar-default">
                                <div class="navbar-header">
                                    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                                        <span class="sr-only">Toggle navigation</span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                        <span class="icon-bar"></span>
                                    </button>
                                </div>
                                <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                                    <ul class="nav navbar-nav">
                                        <li><a href="#">Home</a></li>
                                        <li><a href="#">Serviços</a></li>
                                        <li><a href="#">Técnologias</a></li>
                                        <li><a href="#">Sobre nós</a></li>
                                        <li><a href="#">Blog</a></li>
                                        <li><a href="#">Contato</a></li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</header>
<!--header-->

<div class="container-fluid">
    <?php echo $this->content; ?>
</div>

<!--footer-->
<footer class="footer">
    <div class="container-fluid">
        <div class="row my-row">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="container">
                    <div class="row my-row">
                        <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                            <p>toupweb © 2016 todos os direitos reservados</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>
<!--footer-->

<!-- Scripts -->
<?php echo $this->inlineScript()
    ->prependFile($this->basePath('js/main.min.js'))
    ->prependFile($this->basePath('js/jquery-ui.min.js'))
    ->prependFile($this->basePath('js/bootstrap.min.js'))
    ->prependFile($this->basePath('js/jquery.mask.min.js'))
    ->prependFile($this->basePath('js/jquery.min.js'))
    ->prependFile($this->basePath('js/respond.min.js'), 'text/javascript', array('conditional' => 'lt IE 9',))
    ->prependFile($this->basePath('js/html5shiv.min.js'),   'text/javascript', array('conditional' => 'lt IE 9',))
?>

</body>
</html>
